# Vault Token Secret
#
# Create this secret AFTER initializing Vault:
#   kubectl create secret generic vault-token \
#     --from-literal=token=<YOUR_ROOT_TOKEN> \
#     -n sunbird-rc
#
# Or apply this file after updating the token:
#
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: sunbird-rc
type: Opaque
stringData:
  token: "REPLACE_WITH_VAULT_ROOT_TOKEN"
