apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-portal-nginx-config
  namespace: sunbird-rc-namespace
data:
  default.conf: |
    server {
        listen 80;

        location /admin/ {
                alias /usr/share/nginx/html/admin/;
                index index.html index.htm;
                try_files $uri $uri/ /admin/index.html;
                sub_filter '<base href="/">' '<base href="/admin/">';
                sub_filter_once on;
                sub_filter_types text/html;
        }

        location /registry/ {
              proxy_pass http://registry:8081/;
        }

        location /auth/ {
              proxy_pass          http://keycloak:8080/auth/;
              proxy_set_header    Host $host;
              proxy_set_header    X-Real-IP $remote_addr;
              proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header    X-Forwarded-Proto $scheme;
              proxy_set_header    X-Forwarded-Host $host;
              proxy_set_header    X-Forwarded-Port $server_port;

              proxy_redirect http://keycloak:8080/ http://$host:$server_port/;
        }

        error_page   500 502 503 504  /50x.html;

        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: sunbird-rc-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
        - name: admin-portal
          image: ghcr.io/sunbird-rc/sunbird-rc-admin-portal:main
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_URL
              value: "http://registry:8081"
            - name: KEYCLOAK_URL
              value: "http://keycloak:8080/auth"
          volumeMounts:
            - name: admin-portal-nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /admin/
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: admin-portal-nginx-config
          configMap:
            name: admin-portal-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: sunbird-rc-namespace
spec:
  selector:
    app: admin-portal
  ports:
    - port: 3001
      targetPort: 80
