apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-gen-service
  namespace: sunbird-rc-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id-gen-service
  template:
    metadata:
      labels:
        app: id-gen-service
    spec:
      containers:
        - name: id-gen-service
          image: ghcr.io/sunbird-rc/id-gen-service:v2.0.2
          ports:
            - containerPort: 8088
          env:
            - name: spring.datasource.url
              value: "jdbc:postgresql://db:5432/registry"
            - name: spring.flyway.baseline-on-migrate
              value: "true"
            - name: autocreate.new.seq
              value: "true"
            - name: idformat.from.mdms
              value: "false"
            - name: egov.mdms.provider
              value: "org.egov.id.masterdata.provider.DBMasterDataProvider"
          readinessProbe:
            httpGet:
              path: /egov-idgen/health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: id-gen-service
  namespace: sunbird-rc-namespace
spec:
  selector:
    app: id-gen-service
  ports:
    - port: 8088
      targetPort: 8088
