apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sunbird-rc-namespace

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - vault.yaml
  - keycloak.yaml
  - elasticsearch.yaml
  - did-services.yaml
  - registry.yaml
  - supporting-services.yaml
  - nginx.yaml
  # Additional services
  - claim-ms.yaml
  - encryption-service.yaml
  - id-gen-service.yaml
  - notification-ms.yaml
  - metrics.yaml
  - admin-portal.yaml
  - bulk-issuance.yaml
  - digilocker.yaml
