name: Deploy to Test Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-to-test
  cancel-in-progress: false

jobs:
  build-push:
    name: Build and Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          token: ${{ secrets.GH_PAT }}
          path: composite-actions
          ref: 0.0.10

      - name: Docker Build Registry
        uses: ./composite-actions/.github/actions/docker-build
        with:
          app-name: "sunbird-rc"
          service-name: "registry"
          dockerfile-location: "Dockerfile.registry"
          cluster-name: "test"

      - name: Docker Push Registry
        uses: ./composite-actions/.github/actions/docker-push
        with:
          app-name: "sunbird-rc"
          service-name: "registry"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_REGISTRY }}
          cluster-name: "test"

      - name: Set Dashboard OAuth Credentials
        working-directory: src
        run: |
          echo "VITE_OAUTH_CLIENT_ID=${{ secrets.VITE_OAUTH_CLIENT_ID }}" > dashboard/.env
          echo "VITE_OAUTH_CLIENT_SECRET=${{ secrets.VITE_OAUTH_CLIENT_SECRET }}" >> dashboard/.env

      - name: Docker Build Nginx
        uses: ./composite-actions/.github/actions/docker-build
        with:
          app-name: "sunbird-rc"
          service-name: "nginx"
          dockerfile-location: "Dockerfile.nginx"
          cluster-name: "test"

      - name: Docker Push Nginx
        uses: ./composite-actions/.github/actions/docker-push
        with:
          app-name: "sunbird-rc"
          service-name: "nginx"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_REGISTRY }}
          cluster-name: "test"

  rollout:
    name: Rollout to Test Cluster
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          token: ${{ secrets.GH_PAT }}
          path: composite-actions
          ref: 0.0.10

      - name: Rollout Registry
        uses: ./composite-actions/.github/actions/k8s-rollout
        with:
          app-name: "sunbird-rc"
          deployment-name: "registry"
          container-name: "registry"
          cluster-name: "test"
          namespace-name: "sunbird-rc-namespace"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_K8S }}

      - name: Rollout Nginx
        uses: ./composite-actions/.github/actions/k8s-rollout
        with:
          app-name: "sunbird-rc"
          deployment-name: "nginx"
          container-name: "nginx"
          cluster-name: "test"
          namespace-name: "sunbird-rc-namespace"
          gcloud-sa: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_K8S }}
